### ISSUE TITLE
model/yolo.py

### ISSUE THREAD

**Issue by china56321** [hhaAndroid/yolov5-comment#1]
请问为什么这里要乘以2，减0.5
y[..., 0:2] = (y[..., 0:2] * 2. - 0.5 + self.grid[i].to(x[i].device)) * self.stride[i]  # xy
y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh

**Comment by hhaAndroid** [comment]
建议先阅读 https://zhuanlan.zhihu.com/p/183838757 
因为希望输出的范围是-0.5到1.5之间，而网络预测范围是0-1，所以需要转化
